export const ADD_DATA = "ADD_DATA";
export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_REJECT = 'ADD_ADMIN_REJECT';

// get 
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const FAILURE_DATA = 'FAILURE_DATA';

export const DELETE_ADMIN = 'DELETE_ADMIN';

export const UPDATE_ADMIN_REQUEST = 'UPDATE_ADMIN_REQUEST';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_ADMIN_REJECT = 'UPDATE_ADMIN_REJECT';

